### ISSUE TITLE
Bug i `googleEvents`-processoren

### ISSUE THREAD

**Issue by bjorn-iversen** [knowit/Dataplattform#449]
Følgende feilmelding kommer fra CloudFormation:
```
[ERROR] ValueError: Error converting column "event_button_names" to bytes using encoding UTF8. Original error: bad argument type for built-in operation
Traceback (most recent call last):
  File "/var/task/dataplattform/common/handlers/process.py", line 67, in __call__
    *self.call_wrapped(s3_data, event)
  File "/var/task/dataplattform/common/handlers/process.py", line 132, in update_tables
    append=table_exists)
  File "/var/task/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/var/task/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/var/task/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/var/task/pandas/io/parquet.py", line 199, in write
    **kwargs,
  File "/var/task/fastparquet/writer.py", line 1023, in write
    compression=compression, fmd=fmd)
  File "/var/task/fastparquet/writer.py", line 669, in make_part_file
    rg = make_row_group(f, data, schema, compression=compression)
  File "/var/task/fastparquet/writer.py", line 657, in make_row_group
    compression=comp)
  File "/var/task/fastparquet/writer.py", line 535, in write_column
    repetition_data, definition_data, encode[encoding](data, selement), 8 * b'\x00'
  File "/var/task/fastparquet/writer.py", line 347, in encode_plain
    out = convert(data, se)
  File "/var/task/fastparquet/writer.py", line 279, in convert
    '%s' % (data.name, ct, e))
```

**Comment by torjohannessen** [comment]
Finner ikke at detter problem lenger. Lukker den.
